import Head from "next/head";
import { useEffect, useState, useCallback } from "react";
import AddComment from "../components/AddComment";
import CommentMain from "../components/CommentMain";
import ModalDelete from "../components/ModalDelete";

export default function Home() {
  const [comments, setComments] = useState([]);
  const [currentUser, setCurrentUser] = useState({});

  const fetchCommentsHandler = useCallback(async () => {
    const response = await fetch("/data.json");
    const data = await response.json();

    setComments(data.comments);
    setCurrentUser(data.currentUser);
  }, []);

  useEffect(() => {
    fetchCommentsHandler();
  }, [fetchCommentsHandler]);

  return (
    <div>
      <Head>
        <title>Interactive Comments Section</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/images/favicon-32x32.png' />
      </Head>
      <ModalDelete />
      <main className='mx-4 my-8 max-w-[730px] md:mx-auto md:mt-16'>
        {/* Comments Section */}
        {comments.map((comment) => {
          return (
            <CommentMain
              comment={comment}
              currentUser={currentUser}
              key={comment.id}
            />
          );
        })}

        {/* Add Comment */}
        <AddComment currentUser={currentUser} />
      </main>

      <footer></footer>
    </div>
  );
}
