import Head from "next/head";
import { useEffect, useState, useCallback } from "react";
import AddComment from "../components/AddComment";
import CommentMain from "../components/CommentMain";
import ModalDelete from "../components/ModalDelete";

export default function Home() {
  const [comments, setComments] = useState([]);
  const [currentUser, setCurrentUser] = useState({});
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const fetchCommentsHandler = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetch(
        "https://interactive-comments-408e5-default-rtdb.asia-southeast1.firebasedatabase.app/.json"
      );

      if (!response.ok) {
        throw new Error("Something went wrong!");
      }

      const data = await response.json();

      const ids = Object.keys(data.comments);
      const commentsArray = Object.values(data.comments);

      commentsArray.map((item, i) => {
        if (
          typeof item.replies === "object" &&
          !Array.isArray(item.replies) &&
          item.replies !== null
        ) {
          const items = Object.values(item.replies);

          items.map((entry, i) => {
            entry.id = Object.keys(item.replies)[i];
          });

          item.replies = items;
        }

        return (item.id = ids[i]);
      });

      setComments(commentsArray);
      setCurrentUser(data.currentUser);
    } catch (error) {
      setError(error.message);
    }
    setIsLoading(false);
  }, []);

  useEffect(() => {
    fetchCommentsHandler();
  }, [fetchCommentsHandler]);

  const addCommentHandler = async (addedComment) => {
    const response = await fetch(
      "https://interactive-comments-408e5-default-rtdb.asia-southeast1.firebasedatabase.app/comments.json",
      {
        method: "POST",
        body: JSON.stringify(addedComment),
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    fetchCommentsHandler();
  };

  const deleteCommentHandler = async (id) => {
    await fetch(
      "https://interactive-comments-408e5-default-rtdb.asia-southeast1.firebasedatabase.app/comments/" +
        id +
        ".json",
      {
        method: "DELETE",
      }
    );

    fetchCommentsHandler();
  };

  const deleteReplyHandler = async (commentId, replyId) => {
    await fetch(
      "https://interactive-comments-408e5-default-rtdb.asia-southeast1.firebasedatabase.app/comments/" +
        commentId +
        "/replies/" +
        replyId +
        ".json",
      {
        method: "DELETE",
      }
    );

    fetchCommentsHandler();
  };

  const updateCommentHandler = async (id, updatedComment) => {
    console.log("Updating comment of id: " + id);

    const response = await fetch(
      "https://interactive-comments-408e5-default-rtdb.asia-southeast1.firebasedatabase.app/comments/" +
        id +
        ".json",
      {
        method: "PATCH",
        body: JSON.stringify(updatedComment),
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    fetchCommentsHandler();
  };

  return (
    <div>
      <Head>
        <title>Interactive Comments Section</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/images/favicon-32x32.png' />
      </Head>
      <ModalDelete
        onDeleteComment={deleteCommentHandler}
        onDeleteReply={deleteReplyHandler}
      />
      {comments.length > 0 && (
        <main className='mx-4 my-8 max-w-[730px] md:mx-auto md:mt-16'>
          {/* Comments Section */}
          {comments.map((comment) => {
            return (
              <CommentMain
                comment={comment}
                currentUser={currentUser}
                key={comment.id}
                onEditComment={updateCommentHandler}
                onFetchComments={fetchCommentsHandler}
              />
            );
          })}

          {/* Add Comment */}
          <AddComment
            currentUser={currentUser}
            onAddComment={addCommentHandler}
          />
        </main>
      )}
    </div>
  );
}
